// file: src/actions/types.js
export const SET_TOKEN = "SET_TOKEN";
export const SELECT_CLASSROOM = "SELECT_CLASSROOM";
export const TOGGLE_MODAL_EDIT_CLASSROOM = "TOGGLE_MODAL_CLASSROOM";
export const TOGGLE_MODAL_DELETE_CLASSROOM = "TOGGLE_MODAL_DELETE_CLASSROOM";
export const SELECT_TEACHER = "SELECT_TEACHER";
export const TOGGLE_MODAL_EDIT_TEACHER = "TOGGLE_MODAL_TEACHER";
export const TOGGLE_MODAL_DELETE_TEACHER = "TOGGLE_MODAL_DELETE_TEACHER";
