// file: src/actions/types.js
export const SET_TOKEN = "SET_TOKEN";

export const CLASSROOM = {
  SET_FETCHING: "SET_FETCHING_CLASSROOM",
  SELECT: "SELECT_CLASSROOM",
  SET_BODY: "SET_BODY_CLASSROOM",
  TOGGLE_MODAL_ADD: "TOGGLE_MODAL_ADD_CLASSROOM",
  TOGGLE_MODAL_EDIT: "TOGGLE_MODAL_EDIT_CLASSROOM",
  TOGGLE_MODAL_DELETE: "TOGGLE_MODAL_DELETE_CLASSROOM",
  TOGGLE_MODAL_SENDMAIL: "TOGGLE_MODAL_SENDMAIL_CLASSROOM"
}
export const ASSISTANT = {
  SELECT: "SELECT_ASSISTANT",
  SET_BODY: "SET_BODY_ASSISTANT",
  SET_FETCHING: "SET_FETCHING_ASSISTANT",
  TOGGLE_MODAL_ADD: "TOGGLE_MODAL_ADD_ASSISTANT",
  TOGGLE_MODAL_EDIT: "TOGGLE_MODAL_EDIT_ASSISTANT",
  TOGGLE_MODAL_DELETE: "TOGGLE_MODAL_DELETE_ASSISTANT"
}
export const TEACHER = {
  SELECT: "SELECT_TEACHER",
  SET_BODY: "SET_BODY_TEACHER",
  SET_FETCHING: "SET_FETCHING_TEACHER",
  TOGGLE_MODAL_ADD: "TOGGLE_MODAL_ADD_TEACHER",
  TOGGLE_MODAL_EDIT: "TOGGLE_MODAL_EDIT_TEACHER",
  TOGGLE_MODAL_DELETE: "TOGGLE_MODAL_DELETE_TEACHER"
}
export const SUPPORTER = {
  SELECT: "SELECT_SUPPORTER",
  SET_BODY: "SET_BODY_SUPPORTER",
  SET_FETCHING: "SET_FETCHING_SUPPORTER",
  TOGGLE_MODAL_ADD: "TOGGLE_MODAL_ADD_SUPPORTER",
  TOGGLE_MODAL_EDIT: "TOGGLE_MODAL_EDIT_SUPPORTER",
  TOGGLE_MODAL_DELETE: "TOGGLE_MODAL_DELETE_SUPPORTER"
}
export const MAILTEMPLATE = {
  SELECT: "SELECT_MAILTEMPLATE",
  SET_BODY: "SET_BODY_MAILTEMPLATE",
  SET_FETCHING: "SET_FETCHING_MAILTEMPLATE",
  TOGGLE_MODAL_ADD: "TOGGLE_MODAL_ADD_MAILTEMPLATE",
  TOGGLE_MODAL_EDIT: "TOGGLE_MODAL_EDIT_MAILTEMPLATE",
  TOGGLE_MODAL_DELETE: "TOGGLE_MODAL_DELETE_MAILTEMPLATE",
  TOGGLE_MODAL_PREVIEW: "TOGGLE_MODAL_PREVIEW_MAILTEMPLATE"
}
