# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-07 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bcm_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('date_post_BCM', models.DateTimeField(blank=True, null=True)),
                ('examination_date', models.DateTimeField(blank=True, null=True)),
                ('class_link', models.TextField()),
                ('document_link', models.TextField()),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_course.Assistant', to_field='topica_email')),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_course.Supporter')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_course.Teacher', to_field='topica_email')),
            ],
            options={
                'ordering': ('subject_name',),
            },
        ),
        migrations.CreateModel(
            name='Weekreport_Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('week_post', models.CharField(max_length=5)),
                ('total_post', models.CharField(max_length=5)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_course.Assistant', to_field='topica_email')),
            ],
            options={
                'ordering': ('class_code',),
            },
        ),
        migrations.CreateModel(
            name='Weekreport_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('week_post', models.CharField(max_length=5)),
                ('total_post', models.CharField(max_length=5)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_course.Teacher', to_field='topica_email')),
            ],
            options={
                'ordering': ('class_code',),
            },
        ),
    ]
