# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-11 03:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('school', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=20)),
                ('class_name', models.TextField()),
                ('class_subject', models.TextField()),
                ('estimated_students', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('test_date', models.DateTimeField()),
                ('teacher_name', models.TextField()),
                ('teacher_account', models.CharField(max_length=40)),
                ('assistant_name', models.TextField(blank=True)),
                ('assistant_account', models.CharField(max_length=40)),
                ('teacher_note', models.TextField(blank=True)),
                ('assistant_note', models.TextField(blank=True)),
                ('change_note', models.TextField(blank=True)),
                ('supporter', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
